spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ems_integration_application
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ${LIQUIBASE_CONTEXTS}

cloud:
  aws:
    region:
      auto: true
      use-default-aws-region-chain: true
    credentials:
      use-default-aws-credentials-chain: true

sqs:
  approved-proxy-application-queue-name: ${SQS_APPROVED_PROXY_APPLICATION_QUEUE_NAME}
  approved-postal-application-queue-name: ${SQS_APPROVED_POSTAL_APPLICATION_QUEUE_NAME}
  deleted-proxy-application-queue-name: ${SQS_DELETED_PROXY_APPLICATION_QUEUE_NAME}
  deleted-postal-application-queue-name: ${SQS_DELETED_POSTAL_APPLICATION_QUEUE_NAME}

sts:
  endpoint: ${STS_ENDPOINT}

feature-toggles: